### PR TITLE
SemVer

### PR DESCRIPTION
**Pull request by UnknownNull**

### CODE REVIEW

**Comment by ItsToxicGG** [comment]
Could you explain what you have changed?

**Comment by UnknownNull** [comment]
Some bugs have been fixed and the database connection and the way the plugin works have been tested by phpstorm and pocketmine auxiliary libraries and it works correctly.

From now on, versioning should follow semantic versioning. Because this will be a big project.

☜(ﾟヮﾟ☜)

**Comment by ItsToxicGG** [comment]
i just review it and seems to be good

**Comment by ItsToxicGG** [comment]
and im working on the auth system

**Comment by UnknownNull** [comment]
I also created a new folder to house the helper libraries and put formui in it

**Comment by ItsToxicGG** [comment]
oki, expect auth system to be done in 30 - 50 mins time

**Comment by UnknownNull** [comment]
I am a little unfamiliar with GitHub. I try to learn more about it to do better

**Pull request merged**
